backend:
  name: git-gateway
  branch: master
site_url: https://complimax.netlify.app

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog_metadata"
    label: "Blog Posts (Edit as Raw CSV)"
    description: "Directly edit the metadata-blog.csv file here. Be careful with commas and quotes."
    files:
      - name: "blog_csv_content"
        label: "Blog CSV File"
        file: "metadata-blog.csv"
        format: "frontmatter"
        frontmatter_delimiters:
          - "---"
          - "---"
        fields:
          - name: "body"
            label: "CSV Content"
            widget: "markdown"
            buttons: [] 
            editor_components: [] 

  - name: "posts"
    label: "All Blog Post Files"
    folder: "blogs"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - name: "body"
        label: "Full Blog Post HTML"
        widget: "html"
        hint: "Paste the full HTML for the blog post here, including <!DOCTYPE>, <html>, <head>, and <body> tags."